<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectBaseVersion>1.0</ProjectBaseVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <OutputType>Exe</OutputType>
    <Description>Command line Counter-Strike 2 Workshop manager</Description>
    <AssemblyName>CS2WorkshopManager-CLI</AssemblyName>
    <PublishAot Condition="'$(Configuration)' != 'Debug'">true</PublishAot>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CS2WorkshopManager\CS2WorkshopManager.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- the licence ships next to the executable -->
    <None Include="..\LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
