<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectBaseVersion>1.0</ProjectBaseVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Description>Packs a compiled addon from "game/csgo_addons" and publishes it to Steam.</Description>
    <IsAotCompatible Condition="'$(Configuration)' != 'Debug'">true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.16" />
    <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    <PackageReference Include="ValvePak" Version="6.0.0.182" />
    <PackageReference Include="ValveResourceFormat" Version="20.0.6980" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Steamworks\Steamworks.csproj" />
  </ItemGroup>
</Project>
